### PR TITLE
Chef 17 updates

### PR DESCRIPTION
**Pull request by detjensrobert**
# Description

Chef 17 requires resources to enable [unified_mode](https://docs.chef.io/unified_mode/) in preparation for Chef 18 when it will be the default mode.

This PR also applies the latest Cookstyle corrections and also cleans up the cookbook and testing infrastructure to use modern standards and tools.

## Changes

This PR should have no outward-facing changes, but does remove support for EOL platforms (< Ubuntu 18.04) and Chef versions (< 15.3)

- Remove legacy platform checks
- Enable `unified_mode` 
- Apply latest cookstyle
- convert integration tests to InSpec

### CODE REVIEW

**Comment by detjensrobert** [comment]
@atomic-penguin friendly ping to review this :)

**Comment by atomic-penguin** [comment]
I'll get around to it. This is a big change, and I'm wrangling with a 3 month old and just now getting back into the swing of things at work having been on parental leave.

**Comment by detjensrobert** [comment]
Oh geez! Take your time then, no worries :)

**Comment by detjensrobert** [comment]
@atomic-penguin Have you had some time to look at this yet?

**Comment by atomic-penguin** [comment]
@detjensrobert I'll work on reviewing it this weekend.

**Comment by atomic-penguin** [comment]
@detjensrobert I sent you an email to your GH registered address. Let me know what you wish to do.

**Review by atomic-penguin — APPROVED** [review]

**Pull request merged**
